[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node dist/server/fastmcp-server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production", LOG_LEVEL = "info" }

[environments.staging]
variables = { NODE_ENV = "staging", LOG_LEVEL = "debug" }