name: ✨ Feature Request
description: Suggest a new feature for the MCP server
title: "[FEATURE] "
labels: ["enhancement", "needs-discussion"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: checkboxes
    id: area
    attributes:
      label: Feature Area
      description: Which area would this feature enhance?
      options:
        - label: EasyPost shipping capabilities
        - label: Veeqo inventory management
        - label: AI-powered optimization
        - label: FastMCP server functionality
        - label: Monitoring and observability
        - label: Developer experience
        - label: Documentation

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: As a developer/user, I need... because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternatives?
      placeholder: Other approaches could be...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the feature request
