name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.0

      - name: Use Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint:check

      - name: Type check
        run: pnpm run type-check

      - name: Run tests
        env:
          NODE_ENV: test
          LOG_LEVEL: error
          EASYPOST_API_KEY: mock-easypost-key
          VEEQO_API_KEY: mock-veeqo-key
        run: pnpm run test:ci

      - name: Build
        run: pnpm run build

